### ISSUE TITLE
SASS Compass 雪碧图合并

### ISSUE THREAD

**Issue by hahnzhu** [hahnzhu/hahnzhu.github.com#39]
Compass 自动合成雪碧图在应对有大量图片的 H5 项目上能够节省很大的人力，下面介绍两种写法。

**Comment by hahnzhu** [comment]
## 第一种
```sass
@charset "utf-8";
@import "compass/utilities/sprites";	// 雪碧图生成
@import "compass/css3/background-size";	// Include helper to calc background size

// 第一种用法
$icons-layout: smart; 			// icon 排列方式，必须写在 @import 前，其他值：smart、vertical、diagonal
$icons-spacing: 10px;			// 设置雪碧图边距，不过实测无效（因为 smart 与 spacing 不能同时用）
$icons-sort-by: 'height';		// 根据 width 或 height 排序
$icons-sprite-dimensions: true;	// 自动获取 width 和 height，如有这个则不需要 icons-sprite-width/height
@import "icons/*.png";  		// 生成雪碧图

// @include all-icons-sprites;  // 导入所有图标的样式

.somediv {
  height: icons-sprite-height(crown)/2;
  width: icons-sprite-width(crown)/2;

  @include retina-sprite(cloud);
}
```

**Comment by hahnzhu** [comment]
## 第二种

```scss
@mixin retina-sprite($sprite, $name) { 

	$imgurl: sprite-file($sprite, $name);
	$pos: sprite-position($sprite, $name);

	width: image-width($imgurl) / 2;
	height: image-height($imgurl) / 2;

	background-image: sprite-url($sprite);
	background-position: nth($pos, 1) / 2 nth($pos, 2) / 2;

	@include background-size(ceil(image-width(sprite-path($sprite)) / 2) auto);
}
```
